---
version: '3'
services:
  main:
    deploy:
      restart_policy:
        condition: on-failure
    image: europe-west1-docker.pkg.dev/ci-30-162810/main/postgresql:16.0v0.1.0
    ports:
    - 5432/tcp
    restart: on-failure
