---
services:
  main:
    command: /usr/local/bin/start-container.sh
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - TRANSACTION_ISOLATION_LEVEL=${TRANSACTION_ISOLATION_LEVEL:-REPEATABLE-READ}
    image: europe-west1-docker.pkg.dev/ci-30-162810/main/mariadb:10.3v0.3.2
    ports:
      - 3306/tcp
      - 22/tcp
    restart: on-failure
version: '3'
