---
services:
  main:
    command: /home/camunda/start_container.sh
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_TYPE=${DATABASE_TYPE}
    image: registry.camunda.cloud/team-cambpm/websphere9:7.16.0-alpha1-ee
    ports:
      - 9060/tcp
      - 9080/tcp
    restart: on-failure
version: '3'
