---
services:
  main:
    deploy:
      restart_policy:
        condition: on-failure
    image: europe-west1-docker.pkg.dev/ci-30-162810/main/mariadb:11.8v1.0.0
    ports:
      - 3306/tcp
    restart: on-failure
version: '3'
