---
services:
  main:
    command: /home/camunda/start_container.sh
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_TYPE=${DATABASE_TYPE}
    image: registry.camunda.cloud/team-cambpm/weblogic12r2:7.17.0-alpha2-ee
    ports:
      - 7001/tcp
    restart: on-failure
version: '3'
