---
services:
  main:
    deploy:
      restart_policy:
        condition: on-failure
    image: europe-west1-docker.pkg.dev/ci-30-162810/main/mssql:2017v0.1.1
    ports:
      - 1433/tcp
    restart: on-failure
version: '3'
