services:
  main:
    deploy:
      restart_policy:
        condition: on-failure
    environment: []
    image: europe-west1-docker.pkg.dev/ci-30-162810/main/cockroachdb:20.1v0.1.3
    ports:
      - 26257/tcp
      - 8080/tcp
    restart: on-failure
version: '3'
