---
services:
  main:
    command: /usr/local/bin/start-container.sh
    deploy:
      restart_policy:
        condition: on-failure
    image: europe-west1-docker.pkg.dev/ci-30-162810/main/mariadb:g25v0.3.2
    ports:
      - 3306/tcp
      - 22/tcp
    restart: on-failure
version: '3'
