---
services:
  main:
    command: /home/camunda/start_container.sh
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
    image: registry.camunda.com/camunda-ci-websphere:9.0-db2-11.1-autosetup-7.12.1
    ports:
      - 9060/tcp
      - 9080/tcp
    restart: on-failure
version: '3'
